version: '3.7'

services:

  mysqldb:
    image: mysql
    platform: linux/arm64/v8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: appointmentscheduler
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./target/data:/var/lib/mysql
      - ./src/main/resources:/docker-entrypoint-initdb.d

  backend:
    image: boivin/appointmentschedulerdocker:1.0.6
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    restart: always
    build: .
    depends_on:
      - mysqldb
    platform: linux/arm64/v8
